### ISSUE TITLE
微信服务商 支付结果通知 该如何区分是哪个商户交易的？

### ISSUE THREAD

**Issue by zlyxm** [essensoft/payment#100]
`
                var notify = await _client.ExecuteAsync<WeChatPayUnifiedOrderNotify>(Request, _optionsAccessor.Value);
` 
[https://github.com/essensoft/payment/blob/master/src/Essensoft.AspNetCore.Payment.WeChatPay/WeChatPayNotifyClient.cs#L48](url)
我看是仅WeChatPayOptions.Key有用到，key是微信商户提供的，但如何判断是哪个商户呢？
是需要先解析Request然后再根据MchId判断是那个商户然后再传WeChatPayOptions吗？

**Comment by essensoft-roc** [comment]
通知url加个路由参数 不香吗

**Comment by zlyxm** [comment]
就是属性路由吗？
最开始想的是动态路由，但觉得麻烦。
我先属性路由试下，谢谢了

**Comment by jiwenbu** [comment]
> 就是属性路由吗？ 最开始想的是动态路由，但觉得麻烦。 我先属性路由试下，谢谢了

咋加的？咋处理呢
