### ISSUE TITLE
sample项目的支付宝订单查询接口探讨

### ISSUE THREAD

**Issue by BrisWhite** [essensoft/payment#102]
sample项目的支付宝订单查询接口提一个想法：
不要使用`CertificateExecuteAsync`方法，因为这个方法默认是要检查`AppCert`参数，但是这个参数并不是一定必须的，如果通过示例接口，普通使用者调不通的话，可能会弃用这个库。

**Comment by roc916** [comment]
appsettings有写注意说明啊

https://github.com/essensoft/payment/blob/383f764ca220f8e2007d5ee4dabfb707d96daf57/samples/WebApplicationSample/appsettings.Development.json#L46

另外没配置 `AppCert ` 也会抛出异常提示啊
 https://github.com/essensoft/payment/blob/383f764ca220f8e2007d5ee4dabfb707d96daf57/src/Essensoft.AspNetCore.Payment.Alipay/AlipayClient.cs#L342

**Comment by BrisWhite** [comment]
好的，感谢回复，用的版本比较早了，3.1.8的，当时没有这个提示。
