### ISSUE TITLE
微信支付V3配置文件项：Certificate

### ISSUE THREAD

**Issue by naozikaopa406** [essensoft/payment#106]
用微信支付的工具生成的证书总共有3个文件，.p12  cert.pem key.pem 
我想问的是如果该Key的值不配置成路径，这个.p12的base64是怎么获取？
我试过用cert.pem里面的base64发现在Certificate2.GetRSAPrivateKey()获取到的私钥为null

**Comment by roc916** [comment]
自行将文件转为Base64 String

code:
```
File.ReadAllBytes(fileName);
Convert.ToBase64String(bytes));
```

**Comment by naozikaopa406** [comment]
> File.ReadAllBytes(fileName);
> Convert.ToBase64String(bytes));

谢谢大佬！
