### ISSUE TITLE
Essensoft.AspNetCore.Payment.WeChatPay.V3.Extensions

### ISSUE THREAD

**Issue by heshengli** [essensoft/payment#107]
DateTimeOffset序列化错误
添加
     static HttpClientExtensions()
        {
            jsonSerializerOptions.Converters.Add(new DateTimeOffsetJsonConvert());
        }

 public class DateTimeOffsetJsonConvert : JsonConverter<DateTimeOffset>
    {
        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return DateTimeOffset.Parse(reader.GetString());
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString("yyyy-MM-ddTHH:mm:sszzz"));
        }
    }

**Comment by roc916** [comment]
鉴于文档上为 string[1,64] 类型，于是改回了string。

**Comment by roc916** [comment]
感谢
