### ISSUE TITLE
Why no longer support .net standard 2.0 ?

### ISSUE THREAD

**Issue by John0King** [essensoft/payment#20]

**Comment by Caskia** [comment]
希望能支持 .net standard 2.0.
能说下什么地方造成了必须使用aspnetcore?

**Comment by EssenRoc** [comment]
支持.net standard 2.0. 能够带来些什么吗？Essensoft.AspNetCore.Payment 的定位本就服务是于AspNetCore呀

**Comment by John0King** [comment]
@EssenRoc   支持 .net standard 可以让   asp.net core on .net framework 的项目用 ， 至少目前所有的 asp.net core 框架 都是建立在 .netstandard 2.0 上的（3.0 还没来）。
不过 @Caskia  好像不是这种情况

**Comment by Caskia** [comment]
如果基于.netstandard，你的库更具备通用性，一些非netcoreapp的基础库也可以引用。如果我开发的并不是一个web程序，而是手机那么这个库就没法适应了

**Comment by EssenRoc** [comment]
> 如果基于.netstandard，你的库更具备通用性，一些非netcoreapp的基础库也可以引用。如果我开发的并不是一个web程序，而是手机那么这个库就没法适应了

可这本就是后端领域，并不应该在手机上执行阿...

**Comment by Caskia** [comment]
https://stackoverflow.com/questions/42939454/what-is-the-difference-between-net-core-and-net-standard-class-library-project

**Comment by Caskia** [comment]
后端应用并不限于netcoreapp啊。

**Comment by John0King** [comment]
@Caskia 这个库依赖 asp.net core 也就是 `Microsoft.AspNetCore.Http` , 尽管可以变成 .net standard 类库， 但是仍然无法在 Xamarin 等 asp.net core 无法运行的环境中使用。
> 但是这个后端的形态并不介于是一个X86操作系统的运行环境并且是netcoreapp啊。可以是跑在arm上的各种os

Target `netcoreapp` 还是 `netstandard` , 不会限制CPU的 architecture , 事实上 .net core 支持 arm平台， 唯独限制的是 在 .net framework 或者 mono 上运行 asp.net core 的这种情况， 只能fork 自己编译。

目前在.net 平台有2个比较大的 框架做web,  一个 是 `System.Web`  另外一个是 `Microsoft.AspNetCore` , 很多人总是把这两个混淆成  .net framework 和 .net core , 实际上根本不是一回事， 他们只是建立在.net 平台上面的两个框架而已， 只是 前者只支持 .net framework 和 mono,  后者因为目标是 .net standard 所以所有的运行时都能运行。

@EssenRoc  我看目前这个项目之所以会target netcoreapp 似乎只是为了解决 版本号的问题，但实际上只需要 用 较低的版本 target .netstarndard 2.0  似乎不会产生问题，除非用到了某些破坏性的变更，  hangfire 都是只依赖 2.0.0 的库 也就是（>=2.0.0）， 这样项目如果是 2.2.0 会使用2.2.0  的包

**Comment by EssenRoc** [comment]
> @Caskia 这个库依赖 asp.net core 也就是 `Microsoft.AspNetCore.Http` , 尽管可以变成 .net standard 类库， 但是仍然无法在 Xamarin 等 asp.net core 无法运行的环境中使用。
> 
> > 但是这个后端的形态并不介于是一个X86操作系统的运行环境并且是netcoreapp啊。可以是跑在arm上的各种os
> 
> Target `netcoreapp` 还是 `netstandard` , 不会限制CPU的 architecture , 事实上 .net core 支持 arm平台， 唯独限制的是 在 .net framework 或者 mono 上运行 asp.net core 的这种情况， 只能fork 自己编译。
> 
> 目前在.net 平台有2个比较大的 框架做web, 一个 是 `System.Web` 另外一个是 `Microsoft.AspNetCore` , 很多人总是把这两个混淆成 .net framework 和 .net core , 实际上根本不是一回事， 他们只是建立在.net 平台上面的两个框架而已， 只是 前者只支持 .net framework 和 mono, 后者因为目标是 .net standard 所以所有的运行时都能运行。
> 
> @EssenRoc 我看目前这个项目之所以会target netcoreapp 似乎只是为了解决 版本号的问题，但实际上只需要 用 较低的版本 target .netstarndard 2.0 似乎不会产生问题，除非用到了某些破坏性的变更， hangfire 都是只依赖 2.0.0 的库 也就是（>=2.0.0）， 这样项目如果是 2.2.0 会使用2.2.0 的包

嗯，你说两点完全就是目前遇到的状况。

**Comment by Caskia** [comment]
@John0King 
> 这个库依赖 asp.net core 也就是 Microsoft.AspNetCore.Http , 尽管可以变成 .net standard 类库， 但是仍然无法在 Xamarin 等 asp.net core 无法运行的环境中使用。

1. 我不太明白你说的无法在Xamarin中运行是什么意思？（https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/net-standard）
2. 关于HTTP的内容可以使用Microsoft.Extensions.Http进行抽象，可以参考（https://github.com/reactiveui/refit）

**Comment by John0King** [comment]
@Caskia 支付有2部分， 一部分是通用的， 也就是 `HttpClient` 跟支付服务上游沟通的部分， 另一部分是不通用的（可以进行抽象， 但总归不如直接获取原生对象方便），这一部分就是 `HttpContext.Request.Form("orderId")` 等，支付服务器推送过来的时候的处理（验证消息啥的）
我说的无法在Xamarin中运行， 就是说的这个第二部分， 再有就是 `System.Web.HttpContext`  和 `Microsoft.AspNetCore.Http.HttpContext`

**Comment by EssenRoc** [comment]
@Caskia 其实我到目前为止，还是不了解你的真实需求是什么。

**Comment by EssenRoc** [comment]
目前分支 [dev-netstandard2_0](https://github.com/essensoft/payment/tree/dev-netstandard2_0) 应该可以跑起来了.

**Comment by Caskia** [comment]
@EssenRoc 
@John0King 
我需要用到的只是一部分请求三方支付的接口，比如下单，查询订单信息，退单。而不需要去处理三方服务的回调。

举个例子，我可以控制一批手机作为后台服务去帮我下单，而回调处理我单独部署在一台有公网地址的主机上。

**Comment by Caskia** [comment]
@EssenRoc 
我只是提个建议可以把对于请求处理的逻辑单独独立出来，毕竟这部分与aspnetcore进行了耦合。有的用户只是想用这个库调用下三方的API而已，并不包含完整的支付流程。

**Comment by EssenRoc** [comment]
实际上这是你对payment的误解，paymnet对于aspnetcore本身是没什么依赖的，完全可以在控制台程序(NET Core 2.1\2.2)上跑

**Comment by Caskia** [comment]
因为刚才你们提到为了处理HttpContext中的Request用到aspnetcore。所以我说可以用Microsoft.Extensions.Http.
因为我是Xamarin无法引用netcoreapp2.2的库，只能使用.netstandard

**Comment by EssenRoc** [comment]
@John0King 说的HttpContext 是指接受通知回调部分.

**Comment by EssenRoc** [comment]
2.4.3 已支持，如果遇到什么问题 可以重新打开继续讨论
