### ISSUE TITLE
支付宝异步会掉老是报错

### ISSUE THREAD

**Issue by wangjjaixp** [Essensoft/Payment#21]
支付宝异步会掉老是报错，但正常支持成功！在支付成功后进行异步回调时会报签名不正确问题，为啥？？
```
using (var rsa = RSA.Create())
            {
                var type = "RSA2" == signType ? HashAlgorithmName.SHA256 : HashAlgorithmName.SHA1;
                rsa.ImportParameters(parameters);
                var request= rsa.VerifyData(Encoding.UTF8.GetBytes(data), Convert.FromBase64String(sign), type, RSASignaturePadding.Pkcs1);
                return request;
            }

```
就这段一直返回false

**Comment by EssenRoc** [comment]
检查公钥，配置支付宝公钥（蚂蚁金服开放平台-开放平台密钥-查看支付宝公钥）

**Comment by wangjjaixp** [comment]
> 检查公钥，配置支付宝公钥（蚂蚁金服开放平台-开放平台密钥-查看支付宝公钥）
公钥都是正常，没有错误

**Comment by EssenRoc** [comment]
能支付只能说明 你把自己的公钥配置到后台了，支付宝服务器能通过验证。你这边验签失败，说明你拿的不是支付宝公钥去验证 或者 验签数据有问题。

**Comment by wangjjaixp** [comment]
> 能支付只能说明 你把自己的公钥配置到后台了，支付宝服务器能通过验证。你这边验签失败，说明你拿的不是支付宝公钥去验证 或者 验签数据有问题。

好的我在看看，公钥是不是真的配置错误了

**Comment by EssenRoc** [comment]
> > 能支付只能说明 你把自己的公钥配置到后台了，支付宝服务器能通过验证。你这边验签失败，说明你拿的不是支付宝公钥去验证 或者 验签数据有问题。
> > 刚认真看了，我的公钥配置没有问题，不知道具体哪里不对

你项目里配置的公钥 是不是蚂蚁金服开放平台里的 是不是 RSA2的

**Comment by EssenRoc** [comment]
是不是PKCS1的

**Comment by wangjjaixp** [comment]
是的没错，都是默认的没有去动他

**Comment by wangjjaixp** [comment]
> 是不是PKCS1的

已经解决了，支付宝公钥和应用公钥原来是有差异的-_-

**Comment by EssenRoc** [comment]
> > 是不是PKCS1的
> 
> 已经解决了，支付宝公钥和应用公钥原来是有差异的-_-
心态大蹦。。。我都说的那么明确了。。。配置支付宝公钥（蚂蚁金服开放平台-开放平台密钥-查看支付宝公钥）

**Comment by wangjjaixp** [comment]
> > > 是不是PKCS1的
> > 
> > 
> > 已经解决了，支付宝公钥和应用公钥原来是有差异的-_-
> > 心态大蹦。。。我都说的那么明确了。。。配置支付宝公钥（蚂蚁金服开放平台-开放平台密钥-查看支付宝公钥）

疏忽了，本以为是一样的东西....两个看上去差不多
