### ISSUE TITLE
WeChat pay `服务商支付` support.

### ISSUE THREAD

**Issue by Anduin2017** [essensoft/payment#32]
Now WeChat payment SDK seems only supports `商户支付`. But we are acting as a `服务商`. I could not find a place to configure `服务商`.

But official WeChat pay document supports it:

https://pay.weixin.qq.com/wiki/doc/api/sl.html

![image](https://user-images.githubusercontent.com/19531547/63565842-41716a80-c59d-11e9-9597-2caa3c4ce462.png)

How can we implement it?

**Comment by EssenRoc** [comment]
https://github.com/essensoft/payment/blob/64a698cdc00d7a35f6d8ca570b8bbd763f26fe16/src/Essensoft.AspNetCore.Payment.WeChatPay/Request/WeChatPayUnifiedOrderRequest.cs#L15

https://github.com/essensoft/payment/blob/64a698cdc00d7a35f6d8ca570b8bbd763f26fe16/src/Essensoft.AspNetCore.Payment.WeChatPay/WeChatPayOptions.cs#L12
