### ISSUE TITLE
关于银联证书配置的问题

### ISSUE THREAD

**Issue by RocherKong** [essensoft/payment#34]
Sample里面没有写appsetting.json 相关内容，想问下银联支付是如何配置的

**Comment by EssenRoc** [comment]
[UnionPayOptions.cs](https://github.com/essensoft/payment/blob/dev/src/Essensoft.AspNetCore.Payment.UnionPay/UnionPayOptions.cs)

**Comment by RocherKong** [comment]
这个配置里面的SignCert 指的是我从 https://merchant.chinapay.com/BIZSS/ 导出来的 .pfx 私钥么？

**Comment by EssenRoc** [comment]
不能确定，我这边是从 merchant.unionpay.com 拿到的测试号

**Comment by RocherKong** [comment]
题外话：我就是没登录进去这个站点，这个merchant.unionpay.com 账号密码要自己注册么？被这银联证书搞得有点脑壳疼
