### ISSUE TITLE
Upgrade to .NET Stanard 2.1 to support .NET Core 3.0

### ISSUE THREAD

**Issue by Anduin2017** [essensoft/payment#35]
Now .NET Standard 2.1 is released:

https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

Any plan to upgrade?

**Comment by Anduin2017** [comment]
Hi, it seems that you already provided a demo under .NET Core 3.0. But the SDK is still based on .NET Standard 2.0.

Now that .NET Standard 2.1 has been released. What about upgrading the project to target .NET Standard 2.1?

**Comment by EssenRoc** [comment]
目前还没看到升级2.1的必要性，升级后仅仅局限3.0+使用，目前可以涵盖2.0~3.0

**Comment by Essensoft-Roc** [comment]
e9f70a70d2f80ca1f27f0382ffe992473e81c9ca
