### ISSUE TITLE
我在abp.net的项目中引入该框架，然后在启动的时候就抛出Method not found

### ISSUE THREAD

**Issue by Newxml** [essensoft/payment#36]
Method not found: 'Void Essensoft.AspNetCore.Payment.Alipay.AlipayOptions.set_AppPrivateKey(System.String)'.

**Comment by EssenRoc** [comment]
请提供更多信息，最好是提供可以复现的项目仓库

**Comment by Newxml** [comment]
https://github.com/Newxml/AlipayMent.git
我重新写了一个demo 出现了一个新问题
请在【JxStudioAPICenter.Core】-【Alipay】-【AlipayManager】填写您可以用于本次测试的appid和公私钥
请将JxStudioAPICenter.Web设为启动项，直接运行 可以在swagger上直接调试
在【JxStudioAPICenter.Core】-【Alipay】-【AlipayException】的15行可以捕获到异常，如果可以的话，请您帮我看一看，非常感谢

**Comment by EssenRoc** [comment]
https://github.com/Newxml/AlipayMent/pull/4
