### ISSUE TITLE
支付宝预授权 通知

### ISSUE THREAD

**Issue by Newxml** [essensoft/payment#37]
我没有在【Essensoft.AspNetCore.Payment.Alipay.Notify】这个命名空间下找到
https://docs.open.alipay.com/20180417160701241302/ckfuuu/
这个网址中的4个对应回调模型，可否新增一下？
![image](https://user-images.githubusercontent.com/34527830/66903629-692cfe00-f035-11e9-848f-62ebbaad8b8d.png)

**Comment by EssenRoc** [comment]
下一步就等待测试了

**Comment by Newxml** [comment]
哈哈，辛苦你了

**Comment by EssenRoc** [comment]
已发布版本，若发现问题随时可以再打开讨论
