### ISSUE TITLE
可以考虑下支持拼多多吗？

### ISSUE THREAD

**Issue by beefsteak** [essensoft/payment#40]
你好，感觉最近拼多多和有赞支付也比较多，可以考虑下支持吗

**Comment by waleywu** [comment]
可以自己写一个，payment插件还是挺好写的

**Comment by Essensoft-Roc** [comment]
是的，可以参考payment，自行开发。主要是我这边也不使用，社区也不活跃，即使开发出来了，后续没办法进行有效维护。

**Comment by waleywu** [comment]
确实使用率不高，微信和支付宝做好就足够了
