### ISSUE TITLE
关于终止维护 [连连支付、京东支付、银联支付、QQ钱包] 通知

### ISSUE THREAD

**Issue by Essensoft-Roc** [essensoft/payment#46]
因社区参与度低，且部分渠道使用人数不多。
现决定终止维护 **[连连支付、京东支付、银联支付、QQ钱包]** 渠道。
后续精力主要集中在维护 **[支付宝、微信支付]** 上。
如果你项目中使用到了相关渠道，建议Fork，自行维护。
希望大家能够谅解。

**Comment by ArmyMedalMei** [comment]
确实应该这样，目前微信和支付宝站大量人群
