### ISSUE TITLE
可否支持多个Core版本,毕竟公司开发不可能第一时间把.Net Core升级到最新版本

### ISSUE THREAD

**Issue by 1344695152** [essensoft/payment#50]

**Comment by Essensoft-Roc** [comment]
用旧版本，精力有限，没办法维护多个版本

**Comment by 1344695152** [comment]
谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Roc"<notifications@github.com&gt;; 
发送时间: 2019年12月25日(星期三) 中午12:03
收件人: "essensoft/payment"<payment@noreply.github.com&gt;; 
抄送: "1344695152"<1344695152@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [essensoft/payment] 可否支持多个Core版本,毕竟公司开发不可能第一时间把.Net Core升级到最新版本 (#50)




用旧版本，精力有限，没办法维护多个版本
