### ISSUE TITLE
能否考虑添加【微信支付分】

### ISSUE THREAD

**Issue by changeHC** [essensoft/payment#52]
[微信支付分](https://pay.weixin.qq.com/wiki/doc/apiv3/payscore.php?chapter=12_2&index=1)

**Comment by ArmyMedalMei** [comment]
能否考虑添加【微信支付分】

**Comment by ArmyMedalMei** [comment]
我发现微信支付金额传递1扫描结果是 0.01元，证明微信支付金额的单位是分？

**Comment by Essensoft-Roc** [comment]
> 我发现微信支付金额传递1扫描结果是 0.01元，证明微信支付金额的单位是分？

是的，其他问题。不要在这个issues 下讨论。谢谢配合。

**Comment by ZUOXIANGE** [comment]
[微信支付分](https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/payscore/chapter1_1.shtml)的接入什么时候能实现呢?

**Comment by roc916** [comment]
先关闭这issues，后续由 #73 跟踪
