### ISSUE TITLE
abp怎么用呢

### ISSUE THREAD

**Issue by 3151036158** [essensoft/payment#63]
我在领域层实现功能,但怎么在web去注入相关的服务呢?
教程是     // 引入Payment 依赖注入
            services.AddAlipay();
            services.AddWeChatPay();

            // 在 appsettings.json(开发环境：appsettings.Development.json) 中 配置选项
            services.Configure<AlipayOptions>(Configuration.GetSection("Alipay"));
            services.Configure<WeChatPayOptions>(Configuration.GetSection("WeChatPay"));

**Comment by Essensoft-Roc** [comment]
abp vnext ?

**Comment by Essensoft-Roc** [comment]
abp vnext 在 WebModule 下 ConfigureServices 注入阿

**Comment by 3151036158** [comment]
不是vnext

**Comment by Essensoft-Roc** [comment]
参考 https://github.com/Newxml/AlipayMent

**Comment by 3151036158** [comment]
谢谢,我直接在web层引用包.然后services.AddWeChatPay();  services.Configure<WeChatPayOptions>(Configuration.GetSection("WeChatPay"));
