### ISSUE TITLE
Question: 请问对于微信子商户支付，除了要在Options参数中额外提供SubAppId和SubMchId应当如何使用呢？

### ISSUE THREAD

**Issue by Anduin2017** [essensoft/payment#67]
Question: 请问对于微信子商户支付，除了要在Options参数中额外提供SubAppId和SubMchId应当如何使用呢？

现在我的使用方法是：

https://github.com/essensoft/payment/blob/015d4a58814c2ac5212a361bbc384d0afb80f841/samples/WebApplicationSample/Controllers/WeChatPayController.cs#L165

对于这里的Value，额外给其赋值子商户Appid和商户Id。看起来似乎没问题。但是这样是正确的使用方法吗？

App端的开发人员说，他们收到的签名是错误的。

**Comment by Essensoft-Roc** [comment]
示例是以普通商户为例的。
若是服务商，调用 WeChatPayAppSdkRequest时，Opt是需要传入子商户的APPID和KEY。
其实建议拿到下单结果就可以传给前端。这部分本应该是在前端吊起微信时做的，为了省事我这边一块做了，当时没考虑到子商户的情况。

**Comment by Essensoft-Roc** [comment]
具体的可以看一下微信的开发文档：https://pay.weixin.qq.com/wiki/doc/api/app/app_sl.php?chapter=8_5

**Comment by Anduin2017** [comment]
好的。明白了。我们自己试试改改。

不过，我建议保持此issue open，直到完全支持子商户支付。

**Comment by Essensoft-Roc** [comment]
这部分是纯APP端的问题...
理论上用了服务商API，就不应该再去碰子商户的KEY，所以这不能支持阿。
这本就应该是APP端做的...

**Comment by Essensoft-Roc** [comment]
后端调用下单 WeChatPayUnifiedOrderRequest 就可以了。拿着 PrepayId APP端实现 WeChatPayAppSdkRequest，

**Comment by Essensoft-Roc** [comment]
微信APP支付发起流程：
1.APP端请求
2.服务端下单[服务商opt]
3.APP端调起微信客户端(拿到下单结果PrepayId，WeChatPayAppSdkRequest)[子商户opt]。

因为普通商户不存在 服务商opt 和 子商户opt的问题，所以示例当中体现为2和3合并了。
子商户要做的就是拆分开这两步。

**Comment by Essensoft-Roc** [comment]
我又翻了下微信文档：https://pay.weixin.qq.com/wiki/doc/api/app/app_sl.php?chapter=8_3

> 服务商后台主要交互说明：
> 
> 1.接收到下单请求后，服务商系统调用微信支付【统一下单API】，微信返回prepay_id等参数，如图步骤2-4所示。
> 
> 2.服务商系统获取到prepay_id后，按照【调起支付API】列表中的参数进行签名(服务商开发注意，appid和partnerid都不是服务商的参数，appid是子商户的应用APPID，partnerid是子商户的商户号)，将数据返回给商户APP端，如图中步骤5-6所示。

似乎是在服务端做的，我尝试实现下

**Comment by Essensoft-Roc** [comment]
nuget 已发布 3.1.5-beta.1，如果方便 希望能协助测试下

**Comment by Anduin2017** [comment]
试了一下，完全没毛病！ 💯 非常棒！ 👍👍👍
