### ISSUE TITLE
请问一下IWeChatPayNotifyClient只能在NETCOREAPP3_1下使用是出于什么目的设计的呢？

### ISSUE THREAD

**Issue by Flyoutwithme** [essensoft/payment#78]
如题，为什么IWeChatPayNotifyClient及其一些相关代码被设计为只在NETCOREAPP3_1下进行编译？

**Comment by Essensoft-Roc** [comment]
1.考虑到早期版本用户的使用习惯和迁移成本
2.相关代码依赖例如: Microsoft.AspNetCore.Mvc、Microsoft.AspNetCore.Http 等 包含在Microsoft.AspNetCore.App 的 包

如果有更好的方法，欢迎PR
