### ISSUE TITLE
xml的xxe漏洞建议修复

### ISSUE THREAD

**Issue by try3** [Essensoft/Payment#9]
原：
var bodyDoc = XDocument.Parse(body).Element("xml");
可修改为：
var bodyDoc =XDocument.Load(new XmlTextReader(new StringReader(xml)) { XmlResolver = null }).Element("xml");

**Comment by EssenRoc** [comment]
早就研究过此问题，并不涉及。`XDocument `默认就是禁用DTD的

**Comment by EssenRoc** [comment]
另外 .net452以上版本(包括.net core)也是默认安全的.
