### ISSUE TITLE
有服务商分账功能就好了

### ISSUE THREAD

**Issue by jhlovett** [essensoft/payment#93]
有服务商分账功能就好了....
https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=24_1&index=1

**Comment by Essensoft-Roc** [comment]
有哦

**Comment by jhlovett** [comment]
实在v3里吗?我用的是master分支的源码,所以没有看到有这个demo

**Comment by Essensoft-Roc** [comment]
目前只有v2

**Comment by jhlovett** [comment]
能不能写个分账的demo,找到~

**Comment by Essensoft-Roc** [comment]
没时间阿。人还在外边呢

**Comment by jhlovett** [comment]
不急的，我的意思是什么时间有空的时候写.
