### ISSUE TITLE
Does not work for PKCS8 private key.

### ISSUE THREAD

**Issue by TanvirArjel** [essensoft/payment#96]
If the generated private key is in  PKCS8 format then `SHA256WithRSA.Sign()` does not work. AliPay's latest tool for generating a private key and public key generate keys in the `PKCS8` format but I see `SHA256WithRSA.Sign()` is using PKCS1.

**Comment by Essensoft-Roc** [comment]
https://opendocs.alipay.com/open/291/105971

**Comment by TanvirArjel** [comment]
@Essensoft-Roc Thank you for the link. How can I change the language in the tool I have downloaded from your link. There is everything is Chinese but I need the GUI in English. Please help me.

**Comment by Essensoft-Roc** [comment]
Chinese Only. 😂

**Comment by TanvirArjel** [comment]
@Essensoft-Roc  I have followed this doc and always getting the following error:

`illegal parameter:OpenapiV2签名字段异常: algorithm=RSA256, keyVersion=2, signature=eJpSrvME1ErhL24L5n10CmcMT39Nq9ZwPEd8ax9ugqo6YBlyYkihZ0CMXwONZbCixwNf61VV0gDChE0II4sh3M4O2egkzEmKqjQAXi3b/38idp/38x8fGP12vI5OHgNPRie/9kJespV973WKmG5X7ENUrtoi9AM9R/EAhGqYB61S0OqUz7rsdreTIYGd8sEQkQZjb4bTwWIuHI0AkbtOVeuJVxXYvKnptyQfPUB0S3APjSQ5LWP9qC+la889S8iBnmtHoXGaJQkVVoJZNmr8iNGDyHFeRKDdXXOb/5xx7FQCuyEeRJUNGNmLQcYQFSkWPu7UE8+A/gZLtvrBz5otFw==`

Here is my sample code:

           AliPayPaymentModel aliPayPaymentModel = _configuration.GetSection("SamplePayment").Get<AliPayPaymentModel>();
            string paymentBody = JsonSerializer.Serialize(aliPayPaymentModel);

            string clientId = _configuration.GetSection("AliPay:ClientId").Value;

            string requestTime = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ");
            string unsignedContent = "POST" + " " + "/ams/sandbox/api/v1/payments/pay" + "\n" + clientId + "." + requestTime
                + "." + paymentBody;

            string privateKey = _configuration.GetSection("AliPay:PrivateKey").Value;
            string publicKey = _configuration.GetSection("AliPay:PublicKey").Value;

            string signature = string.Empty;
            using (RSA rsa = RSA.Create())
            {
                byte[] vs = Convert.FromBase64String(privateKey);
                rsa.ImportPkcs8PrivateKey(vs, out int _);
                signature = Convert.ToBase64String(rsa.SignData(Encoding.UTF8.GetBytes(unsignedContent), HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1));
            }


            HttpContent httpContent = new StringContent(paymentBody, Encoding.UTF8, "application/json");
            _httpClient.DefaultRequestHeaders.Add("Client-Id", clientId);
            _httpClient.DefaultRequestHeaders.Add("Request-Time", requestTime);
            _httpClient.DefaultRequestHeaders.Add("Signature", $"algorithm=RSA256, keyVersion=2, signature={signature}");
            HttpResponseMessage httpResponseMessage = await _httpClient.PostAsync("https://open-na.alipay.com/ams/sandbox/api/v1/payments/pay", httpContent);
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                string repsonseString = await httpResponseMessage.Content.ReadAsStringAsync();

                JsonSerializerOptions JsonSerializerOptions = new JsonSerializerOptions()
                {
                    PropertyNameCaseInsensitive = true
                };

                AliPayPaymentResponseModel aliPayPaymentResponseModel = JsonSerializer.Deserialize<AliPayPaymentResponseModel>(repsonseString, JsonSerializerOptions);
            }

Could you help me please where exactly I doing it wrong?
